attempted to add default interface implementation
cannot proceed due to
Error CS8370 Feature 'default interface implementation' is not available in C# 7.3. Please use language version 8.0 or greater.