commented out the code that caused
Error CS8370 Feature 'default interface implementation' is not available in C# 7.3. Please use language version 8.0 or greater.

error